### ISSUE TITLE
4.10.0 Strange behavior for Goal level calculation on Overview tab

### ISSUE THREAD

**Issue by Cinerar** [Boldy97/ironwood-scripts#20] opened 2024-08-10 13:28 UTC
![image](https://github.com/user-attachments/assets/cad8b694-e011-413d-af2e-b5dde5f8e57b)

**Comment by Boldy97** [comment] 2024-08-11 21:41
This should hopefully be resolved in https://github.com/Boldy97/ironwood-scripts/commit/2f21c15acbafe2f26d144e2c3c43b23740f607e3

The cause is definitely not the level potion, I tried to replicate it.
As soon as the script picked up a higher level for any skill, it tends to stick around, until you refresh.
I made it so when it detects a lower level from anywhere now, it updates correctly.

**Closed by Boldy97** 2024-08-11 21:41 UTC
